### NLP

- Features we will be using out of the collected data to build knn model:
    1. Nutrition
    3. Ingredients
- In order to process the tags and ingredients we have to convert them into numerical representations
- For ingredients we will be using the tf-idf vectorization

#### Pre-requisites

In [141]:
import warnings
warnings.filterwarnings(action="ignore")

#### Import dependencies

In [1]:
import pandas as pd
import numpy as np
import re

#### Get the data

In [2]:
df = pd.read_csv("Dataset_combined.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3595 entries, 0 to 3594
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    3595 non-null   int64
 1   name          3595 non-null   object
 2   ingredients   3595 non-null   object
 3   instructions  3595 non-null   object
 4   nutrition     3595 non-null   object
 5   time          3588 non-null   object
 6   serving_size  3593 non-null   object
 7   tags          3595 non-null   object
dtypes: int64(1), object(7)
memory usage: 224.8+ KB

In [4]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.to_csv("Dataset_combined2.csv")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3571 entries, 0 to 3594
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          3571 non-null   object
 1   ingredients   3571 non-null   object
 2   instructions  3571 non-null   object
 3   nutrition     3571 non-null   object
 4   time          3567 non-null   object
 5   serving_size  3570 non-null   object
 6   tags          3571 non-null   object
dtypes: object(7)
memory usage: 223.2+ KB

In [8]:
df["nutrition"]

0       {'Energy': '195 cal', 'Protein': '10.3 g', 'Ca...
1       {'Energy': '74 cal', 'Protein': '2.6 g', 'Carb...
2       {'Energy': '374 cal', 'Protein': '13.3 g', 'Ca...
3       {'Energy': '92 cal', 'Protein': '0.1 g', 'Carb...
4       {'Energy': '68 cal', 'Protein': '2.3 g', 'Carb...
                              ...
3590    {'Calories ': '495 cal', 'Kilojoules ': '2070 ...
3591    {'Calories ': '546 cal', 'Kilojoules ': '2280 ...
3592    {'Calories ': '380 cal', 'Kilojoules ': '1590 ...
3593                                                   {}
3594    {'Calories ': '449 cal', 'Kilojoules ': '1880 ...
Name: nutrition, Length: 3571, dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3571 entries, 0 to 3594
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          3571 non-null   object
 1   ingredients   3571 non-null   object
 2   instructions  3571 non-null   object
 3   nutrition     3571 non-null   object
 4   time          3567 non-null   object
 5   serving_size  3570 non-null   object
 6   tags          3571 non-null   object
dtypes: object(7)
memory usage: 223.2+ KB

### Extracting Features

#### I. Nutrition

- First we need the nutrition values in per recipe so let's explode them

In [10]:
eval(df["nutrition"][0])  #7 different values

{'Energy': '195 cal',
 'Protein': '10.3 g',
 'Carbohydrates': '30.5 g',
 'Fiber': '7.9 g',
 'Fat': '4.1 g',
 'Cholesterol': '0 mg',
 'Sodium': '8.8 mg'}

In [11]:
eval(df["nutrition"].iloc[-1]) #11 different values

{'Calories ': '449 cal',
 'Kilojoules ': '1880 kJ',
 'Protein ': '38 g',
 'Total fat ': '17 g',
 'Saturated fat ': '6 g',
 'Carbohydrates ': '35 g',
 'Sugar ': '8 g',
 'Dietary fibre ': '5 g',
 'Sodium ': '530 mg',
 'Calcium ': '130 mg',
 'Iron ': '3.5 mg'}

In [21]:
eval(df["nutrition"][1940]) #8 different values

{'kcal': '333 g',
 'fat': '10 g',
 'saturates': '3 g',
 'carbs': '26 g',
 'sugars': '10 g',
 'fibre': '3 g',
 'protein': '36 g',
 'salt': '1.34 g'}

- Since our data is collected from three different sources, there seems to be varying measures of nutrition, let us keep the most basic nutrition values and drop the rest for now. 
- Later, we could also impute the additional nutrients like calcium, iron using a food nutrition dataset

In [22]:
#feature set
features = df[["ingredients","nutrition","tags"]]

In [23]:
features.head(3)

,ingredients,nutrition,tags
0,['2 cups sprouted vaal (field beans/ butter be...,"{'Energy': '195 cal', 'Protein': '10.3 g', 'Ca...","['Non-stick Pan', 'Boiled Indian recipes', 'Sa..."
1,"['2 1/2 cups capsicum cubes', '1/2 cup low-fat...","{'Energy': '74 cal', 'Protein': '2.6 g', 'Carb...","['Non Stick Kadai Veg', 'Antioxidant Rich Indi..."
2,"['1 cup sliced onions', '3 tbsp roughly choppe...","{'Energy': '374 cal', 'Protein': '13.3 g', 'Ca...","['Non-stick Pan', 'Indian Dinner', 'Indian Lun..."

In [24]:
features["nutrition"]

0       {'Energy': '195 cal', 'Protein': '10.3 g', 'Ca...
1       {'Energy': '74 cal', 'Protein': '2.6 g', 'Carb...
2       {'Energy': '374 cal', 'Protein': '13.3 g', 'Ca...
3       {'Energy': '92 cal', 'Protein': '0.1 g', 'Carb...
4       {'Energy': '68 cal', 'Protein': '2.3 g', 'Carb...
                              ...
3590    {'Calories ': '495 cal', 'Kilojoules ': '2070 ...
3591    {'Calories ': '546 cal', 'Kilojoules ': '2280 ...
3592    {'Calories ': '380 cal', 'Kilojoules ': '1590 ...
3593                                                   {}
3594    {'Calories ': '449 cal', 'Kilojoules ': '1880 ...
Name: nutrition, Length: 3571, dtype: object

In [25]:
# apply a function to this in order to convert values from string to numeric and 
# remove the units like 'cal' and 'g'
# nutrients we are gonna keep: 
# ['Calories', 'Protein', 'Carbohydrates', 'Fiber', 'Fat', 'Sodium']

import ast

def nutrition_preprocessing(nutrients_series):
    mapped = {"calories": None, "protein":None, "carbohydrates":None, "fiber":None, "fat":None, "sodium":None}
    to_dict = ast.literal_eval(nutrients_series)
    for key,value in to_dict.items():
        prep_key = key.strip().lower()
        cleaned = re.sub(r'[^\d\.]', '', value)
        if cleaned == "":  # Some values in carbohydrates are like "N/A"
            continue
        if prep_key in ["calories","energy","kcal"]:
            mapped["calories"]= float(cleaned)
        if prep_key == "protein":
            mapped["protein"]= float(cleaned)
        if prep_key in ["carbohydrates","carbs"]:
            mapped["carbohydrates"]= float(cleaned)
        if prep_key in ["fiber","dietary fibre","fibre"]:
            mapped["fiber"]= float(cleaned)    
        if prep_key in ["fat","total fat"]:
            mapped["fat"]= float(cleaned)
        if prep_key in ["sodium","salt"]:
            mapped["sodium"]= float(cleaned)
    return mapped

In [26]:
cleaned = features["nutrition"].apply(nutrition_preprocessing)

In [27]:
exploded_df = pd.json_normalize(cleaned)

In [28]:
exploded_df

      calories  protein  carbohydrates  fiber   fat  sodium
0        195.0     10.3           30.5    7.9   4.1     8.8
1         74.0      2.6            9.5    3.2   2.9    21.8
2        374.0     13.3           16.4    4.2  28.4    98.6
3         92.0      0.1            0.4    0.0  10.0     0.0
4         68.0      2.3            3.9    3.4   5.3   114.5
...        ...      ...            ...    ...   ...     ...
3566     495.0     19.0           45.0   14.0  25.0   650.0
3567     546.0     23.0           50.0   12.0  28.0   770.0
3568     380.0     16.0           55.0   11.0   9.0   350.0
3569       NaN      NaN            NaN    NaN   NaN     NaN
3570     449.0     38.0           35.0    5.0  17.0   530.0

[3571 rows x 6 columns]

In [29]:
# add the exploded column to features 
features_exploded = features.drop("nutrition", axis=1).join(exploded_df)

In [30]:
features_exploded.head(3)

,ingredients,tags,calories,protein,carbohydrates,fiber,fat,sodium
0,['2 cups sprouted vaal (field beans/ butter be...,"['Non-stick Pan', 'Boiled Indian recipes', 'Sa...",195.0,10.3,30.5,7.9,4.1,8.8
1,"['2 1/2 cups capsicum cubes', '1/2 cup low-fat...","['Non Stick Kadai Veg', 'Antioxidant Rich Indi...",74.0,2.6,9.5,3.2,2.9,21.8
2,"['1 cup sliced onions', '3 tbsp roughly choppe...","['Non-stick Pan', 'Indian Dinner', 'Indian Lun...",374.0,13.3,16.4,4.2,28.4,98.6

In [31]:
# droping the two na values because of missing carbohydrate found while extracting 
# nutrients
features_exploded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3571 entries, 0 to 3594
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ingredients    3571 non-null   object
 1   tags           3571 non-null   object
 2   calories       3519 non-null   float64
 3   protein        3520 non-null   float64
 4   carbohydrates  3516 non-null   float64
 5   fiber          3519 non-null   float64
 6   fat            3520 non-null   float64
 7   sodium         3504 non-null   float64
dtypes: float64(6), object(2)
memory usage: 380.1+ KB

In [32]:
features_exploded[features_exploded.isnull().any(axis=1)].tail(3)

,ingredients,tags,calories,protein,carbohydrates,fiber,fat,sodium
3592,"['1', ', grated', '1 carrot, grated', '1 large...","['High fibre', 'High iron', 'Low FODMAP recipe...",NaN,NaN,NaN,NaN,NaN,NaN
3593,"['1 cup mesclun or other salad leaves', '1 cup...","['Meals for one', 'No, or minimal, cooking', '...",NaN,NaN,NaN,NaN,NaN,NaN
3594,"['spray oil', '1 tablespoon olive oil', '900g ...","['Diabetes-friendly', '2 vege serves', 'Family...",NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
# We have no option but to drop these rows as nutrient info for them are also missing

In [34]:
features_exploded.dropna(inplace=True)

In [35]:
features_exploded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3499 entries, 0 to 3570
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ingredients    3499 non-null   object
 1   tags           3499 non-null   object
 2   calories       3499 non-null   float64
 3   protein        3499 non-null   float64
 4   carbohydrates  3499 non-null   float64
 5   fiber          3499 non-null   float64
 6   fat            3499 non-null   float64
 7   sodium         3499 non-null   float64
dtypes: float64(6), object(2)
memory usage: 246.0+ KB

In [36]:
nutrients = features_exploded.drop(["ingredients","tags"],axis=1)

In [37]:
nutrients.describe()

,calories,protein,carbohydrates,fiber,fat,sodium
count,3499.000000,3499.000000,3499.000000,3499.000000,3499.000000,3499.000000
mean,241.841669,12.540897,25.876393,5.664087,9.061275,210.307082
std,180.054063,12.998804,18.603114,15.145737,8.541679,317.145876
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,92.000000,2.600000,10.700000,1.800000,2.300000,10.900000
50%,190.000000,6.600000,21.900000,3.900000,6.700000,54.600000
75%,389.000000,20.400000,38.500000,8.000000,13.700000,353.300000
max,2167.000000,79.000000,102.800000,680.000000,74.500000,5829.600000

In [38]:
nutrients.keys()

Index(['calories', 'protein', 'carbohydrates', 'fiber', 'fat', 'sodium'], dtype='object')

- Scaling

In [39]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_nutrients = scaler.fit_transform(nutrients)

In [40]:
scaled_nutrients

array([[-0.26019054, -0.17241722,  0.24857492,  0.14764767, -0.58091433,
        -0.63546746],
       [-0.93230697, -0.76486407, -0.88042967, -0.16271503, -0.72142201,
        -0.594471  ],
       [ 0.7340974 ,  0.05840623, -0.50947102, -0.09668042,  2.26436621,
        -0.35227653],
       ...,
       [ 1.68950258,  0.80473538,  1.29693632,  0.4183896 ,  2.21753032,
         1.76503293],
       [ 0.76742549,  0.26614733,  1.56574694,  0.35235498, -0.00717463,
         0.44053193],
       [ 1.1506985 ,  1.95885262,  0.49050447, -0.04385272,  0.92954324,
         1.00817521]], shape=(3499, 6))

In [41]:
scaled_nutrients_df = pd.DataFrame(scaled_nutrients,columns=nutrients.keys())

In [42]:
scaled_nutrients_df.describe()

,calories,protein,carbohydrates,fiber,fat,sodium
count,3.499000e+03,3.499000e+03,3.499000e+03,3.499000e+03,3.499000e+03,3.499000e+03
mean,-6.498247e-17,-6.498247e-17,-9.747371e-17,-1.624562e-17,2.274387e-16,-9.747371e-17
std,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00,1.000143e+00
min,-1.343353e+00,-9.649111e-01,-1.391170e+00,-3.740258e-01,-1.060982e+00,-6.632189e-01
25%,-8.323227e-01,-7.648641e-01,-8.159151e-01,-2.551635e-01,-7.916759e-01,-6.288450e-01
50%,-2.879639e-01,-4.570995e-01,-2.137793e-01,-1.164908e-01,-2.764810e-01,-4.910338e-01
75%,8.174176e-01,6.046884e-01,6.786719e-01,1.542511e-01,5.431471e-01,4.509387e-01
max,1.069364e+01,5.113440e+00,4.135576e+00,4.452951e+01,7.662203e+00,1.772085e+01

#### 2. Ingredients

In [43]:
sample= features_exploded["ingredients"].sample(10)
# let's start with this sample, then we can apply a cleaning function to the whole column

In [44]:
for s in sample:
    print(s)

['1 tablespoon sunflower oil', 'large handful fresh sage leaves', '4 smoked streaky bacon rashers, chopped', '450g leeks (about 2 medium), finely sliced', '2 cloves garlic, crushed', '225g arborio risotto rice', '2/3 cup dry white wine', '2 very low salt vegetable stock cubes dissolved in 3 cups hot water', '80g soft feta cheese, crumbled']
['1/2 cup chopped bananas', '1 cup whisked fresh curd (dahi)', '1/4 tsp mustard (rai / sarson) powder', '1/2 tsp finely chopped green chillies', '1 tsp powdered sugar', 'salt to taste']
['500g potatoes, peeled and coarsely grated', '175g cubed pancetta or bacon', '1 onion, finely sliced', '6 eggs, separated', '5 tablespoons', '3 tablespoons skim milk', 'bunch fresh chives, snipped', '4 tablespoons reduced sugar and salt tomato sauce, to serve']
['2 tsp soy oil', '2 tsp ginger-garlic (adrak-lehsun) paste', '1/2 cup finely chopped onion', '1/4 tsp turmeric powder (haldi)', '1 tsp coriander-cumin seeds (dhania-jeera) powder', '1 tsp chilli powder', '1/2 tsp garam masala', '1 tsp dried fenugreek leaves  (kasuri methi)', '1 tsp  garam masala', '1/4 cup sliced capsicum', 'fresh tomato pur?e', '1/2 tsp sugar', '2 tbsp low fat cream', 'salt to taste', '2 tbsp chopped coriander (dhania) for garnishing']
['5 tbsp chana dal (split Bengal gram)', '2 tsp oil', '1/4 tsp chopped ginger (adrak)', '1/2 tsp cumin seeds (jeera)', '2 whole dry Kashmiri red chilli , broken into pieces', 'salt to taste', '1/4 cup whisked curds (dahi)', '1/4 tsp mustard seeds ( rai / sarson)', '3 curry leaves (kadi patta)', '1/4 tsp asafoetida (hing)']
['1 cup almond (badam)', '1 cup milk', '1 tbsp ghee', '1/2 cup sugar', '1/2 tsp cardamom (elaichi) powder', 'a few saffron (kesar) strands dissolved in 1 tsp warm', '2 tbsp almond (badam) slivers']
['6 red, green or yellow capsicums', '½ cup white quinoa, rinsed', '2 tablespoons olive oil, plus 1 tablespoon extra to serve', '1 large white onion, thinly sliced', '3 cloves garlic, crushed', '1 large', ', cut into 1cm pieces', '1 teaspoon dried oregano', '1 teaspoon sweet paprika', '350g lean lamb mince', '¼ cup green olives, pitted, coarsely chopped', '2 tablespoons pine nuts, toasted', '¼ cup loosely packed fresh parsley leaves, finely chopped, plus extra to serve', '80g reduced-fat feta, crumbled, to serve', '6 cups salad leaves, to serve']
['1 medium red capsicum', '1 medium yellow capsicum', '1 medium green capsicum', '', '8 whole wheat bread slices or multigrain bread slices', '3/4 tsp oil for brushing', 'salt to taste', '1 tsp dried mixed herbs', '4 big iceberg lettuce leaves', '3/4 cup grated low fat paneer (cottage cheese)', '1 tbsp low fat curds (dahi)', '', '1 tbsp finely chopped parsley or finely chopped coriander (dhania)', '1 tbsp finely chopped dill leaves', '1 tsp finely chopped garlic (lehsun)', '1 tsp finely chopped green chillies', 'salt to taste']
['2 cups chopped spinach (palak)', '1/2 cup brinjal (baingan / eggplant) cubes', '1/2 cup yellow moong dal (split yellow gram)', '1/4 tsp ginger (adrak) paste', '1/4 tsp garam masala', '1/4 tsp turmeric powder (haldi)', 'a pinch of baking soda', 'salt to taste', '2 tsp oil', '1/2 tsp nigella seeds (kalonji)', '1 green chilli , slit', '1/4 tsp turmeric powder (haldi)', '1 tsp lemon juice']
['1 bunch broccolini, trimmed', '1 bunch asparagus, trimmed', '¹⁄³ cup chopped fresh flat-leaf parsley leaves', '2 tablespoons pesto', '¹⁄³ cup olive oil', '2 garlic cloves, crushed', '3', ', coarsely grated', '1 cup wholemeal spelt flour', '1 teaspoon baking powder', '²⁄³ cup reduced-fat grated cheddar cheese', '6 eggs', '½ cup milk']

In [45]:
sample.iloc[0]

"['1 tablespoon sunflower oil', 'large handful fresh sage leaves', '4 smoked streaky bacon rashers, chopped', '450g leeks (about 2 medium), finely sliced', '2 cloves garlic, crushed', '225g arborio risotto rice', '2/3 cup dry white wine', '2 very low salt vegetable stock cubes dissolved in 3 cups hot water', '80g soft feta cheese, crumbled']"

- Right now are ingredients column contains a list of splitted strings but what we need is a list of tokens
- Problems :
    * removing measures like cups and tbsp
    * removing quantities
    * map english and hindi ingredients (paneer --> cottage cheese)
    * lemon juice, flax seeds should be one token 
    * lemmatization

1. Tokenization

In [46]:
def custom_tokenizer(text):
    # Remove quantities and units
    text = re.sub(r'\b\d+/?\d*\b', '', text.lower())  # remove quantities
    text = re.sub(r'\b(?:tsp|tbsp|cup|cups|g|gram|grams|kg|ml|l|oz|teaspoon|tablespoon|pinch)\b', '', text, flags=re.IGNORECASE)

    # Tokenize 
    tokens = re.findall(r'\b[a-zA-Z]+\b', text)
    return tokens

In [47]:
custom_tokenizer(sample.iloc[0])

['sunflower',
 'oil',
 'large',
 'handful',
 'fresh',
 'sage',
 'leaves',
 'smoked',
 'streaky',
 'bacon',
 'rashers',
 'chopped',
 'leeks',
 'about',
 'medium',
 'finely',
 'sliced',
 'cloves',
 'garlic',
 'crushed',
 'arborio',
 'risotto',
 'rice',
 'dry',
 'white',
 'wine',
 'very',
 'low',
 'salt',
 'vegetable',
 'stock',
 'cubes',
 'dissolved',
 'in',
 'hot',
 'water',
 'soft',
 'feta',
 'cheese',
 'crumbled']

In [48]:
for s in sample:
    print(custom_tokenizer(s))

['sunflower', 'oil', 'large', 'handful', 'fresh', 'sage', 'leaves', 'smoked', 'streaky', 'bacon', 'rashers', 'chopped', 'leeks', 'about', 'medium', 'finely', 'sliced', 'cloves', 'garlic', 'crushed', 'arborio', 'risotto', 'rice', 'dry', 'white', 'wine', 'very', 'low', 'salt', 'vegetable', 'stock', 'cubes', 'dissolved', 'in', 'hot', 'water', 'soft', 'feta', 'cheese', 'crumbled']
['chopped', 'bananas', 'whisked', 'fresh', 'curd', 'dahi', 'mustard', 'rai', 'sarson', 'powder', 'finely', 'chopped', 'green', 'chillies', 'powdered', 'sugar', 'salt', 'to', 'taste']
['potatoes', 'peeled', 'and', 'coarsely', 'grated', 'cubed', 'pancetta', 'or', 'bacon', 'onion', 'finely', 'sliced', 'eggs', 'separated', 'tablespoons', 'tablespoons', 'skim', 'milk', 'bunch', 'fresh', 'chives', 'snipped', 'tablespoons', 'reduced', 'sugar', 'and', 'salt', 'tomato', 'sauce', 'to', 'serve']
['soy', 'oil', 'ginger', 'garlic', 'adrak', 'lehsun', 'paste', 'finely', 'chopped', 'onion', 'turmeric', 'powder', 'haldi', 'coriander', 'cumin', 'seeds', 'dhania', 'jeera', 'powder', 'chilli', 'powder', 'garam', 'masala', 'dried', 'fenugreek', 'leaves', 'kasuri', 'methi', 'garam', 'masala', 'sliced', 'capsicum', 'fresh', 'tomato', 'pur', 'e', 'sugar', 'low', 'fat', 'cream', 'salt', 'to', 'taste', 'chopped', 'coriander', 'dhania', 'for', 'garnishing']
['chana', 'dal', 'split', 'bengal', 'oil', 'chopped', 'ginger', 'adrak', 'cumin', 'seeds', 'jeera', 'whole', 'dry', 'kashmiri', 'red', 'chilli', 'broken', 'into', 'pieces', 'salt', 'to', 'taste', 'whisked', 'curds', 'dahi', 'mustard', 'seeds', 'rai', 'sarson', 'curry', 'leaves', 'kadi', 'patta', 'asafoetida', 'hing']
['almond', 'badam', 'milk', 'ghee', 'sugar', 'cardamom', 'elaichi', 'powder', 'a', 'few', 'saffron', 'kesar', 'strands', 'dissolved', 'in', 'warm', 'almond', 'badam', 'slivers']
['red', 'green', 'or', 'yellow', 'capsicums', 'white', 'quinoa', 'rinsed', 'tablespoons', 'olive', 'oil', 'plus', 'extra', 'to', 'serve', 'large', 'white', 'onion', 'thinly', 'sliced', 'cloves', 'garlic', 'crushed', 'large', 'cut', 'into', 'pieces', 'dried', 'oregano', 'sweet', 'paprika', 'lean', 'lamb', 'mince', 'green', 'olives', 'pitted', 'coarsely', 'chopped', 'tablespoons', 'pine', 'nuts', 'toasted', 'loosely', 'packed', 'fresh', 'parsley', 'leaves', 'finely', 'chopped', 'plus', 'extra', 'to', 'serve', 'reduced', 'fat', 'feta', 'crumbled', 'to', 'serve', 'salad', 'leaves', 'to', 'serve']
['medium', 'red', 'capsicum', 'medium', 'yellow', 'capsicum', 'medium', 'green', 'capsicum', 'whole', 'wheat', 'bread', 'slices', 'or', 'multigrain', 'bread', 'slices', 'oil', 'for', 'brushing', 'salt', 'to', 'taste', 'dried', 'mixed', 'herbs', 'big', 'iceberg', 'lettuce', 'leaves', 'grated', 'low', 'fat', 'paneer', 'cottage', 'cheese', 'low', 'fat', 'curds', 'dahi', 'finely', 'chopped', 'parsley', 'or', 'finely', 'chopped', 'coriander', 'dhania', 'finely', 'chopped', 'dill', 'leaves', 'finely', 'chopped', 'garlic', 'lehsun', 'finely', 'chopped', 'green', 'chillies', 'salt', 'to', 'taste']
['chopped', 'spinach', 'palak', 'brinjal', 'baingan', 'eggplant', 'cubes', 'yellow', 'moong', 'dal', 'split', 'yellow', 'ginger', 'adrak', 'paste', 'garam', 'masala', 'turmeric', 'powder', 'haldi', 'a', 'of', 'baking', 'soda', 'salt', 'to', 'taste', 'oil', 'nigella', 'seeds', 'kalonji', 'green', 'chilli', 'slit', 'turmeric', 'powder', 'haldi', 'lemon', 'juice']
['bunch', 'broccolini', 'trimmed', 'bunch', 'asparagus', 'trimmed', 'chopped', 'fresh', 'flat', 'leaf', 'parsley', 'leaves', 'tablespoons', 'pesto', 'olive', 'oil', 'garlic', 'cloves', 'crushed', 'coarsely', 'grated', 'wholemeal', 'spelt', 'flour', 'baking', 'powder', 'reduced', 'fat', 'grated', 'cheddar', 'cheese', 'eggs', 'milk']

* Observations:
    - Stop words still need to be removed 
    - Have to remove verbs like added, chopped, splash, peeled (nltk pos tag)
    - Adverbs like roughly 
    - there are some ingredients that are mentioned both in hindi and english like: 'flour' and 'gehun ka atta', "panner" and "cottage cheeze" (ignore hindi words by filtering from english dictionary)
    - might need to specify n grams as there are some tokens with more than one word so order also matters like "gehun ka atta", "baby spinach" "cottage cheeze", "chocolate chips" (however this will increase vector size)

In [49]:
# pip install spacy
# python -m spacy download en_core_web_sm

In [50]:
import spacy
# load english model 
nlp = spacy.load('en_core_web_sm')

In [51]:
doc = nlp(sample.iloc[0])

In [52]:
type(doc) #this is a spacy object containing tokens

spacy.tokens.doc.Doc

In [53]:
for token in doc:
    print(f"{token.text:<15} | POS: {token.pos_:<10} | Lemma: {token.lemma_}")

[               | POS: X          | Lemma: [
'               | POS: NUM        | Lemma: '
1               | POS: NUM        | Lemma: 1
tablespoon      | POS: NOUN       | Lemma: tablespoon
sunflower       | POS: NOUN       | Lemma: sunflower
oil             | POS: NOUN       | Lemma: oil
'               | POS: PUNCT      | Lemma: '
,               | POS: PUNCT      | Lemma: ,
'               | POS: PUNCT      | Lemma: '
large           | POS: ADJ        | Lemma: large
handful         | POS: NOUN       | Lemma: handful
fresh           | POS: ADJ        | Lemma: fresh
sage            | POS: NOUN       | Lemma: sage
leaves          | POS: VERB       | Lemma: leave
'               | POS: PART       | Lemma: '
,               | POS: PUNCT      | Lemma: ,
'               | POS: PUNCT      | Lemma: '
4               | POS: NUM        | Lemma: 4
smoked          | POS: VERB       | Lemma: smoke
streaky         | POS: ADJ        | Lemma: streaky
bacon           | POS: NOUN       | Lemma: bacon
rashers         | POS: NOUN       | Lemma: rasher
,               | POS: PUNCT      | Lemma: ,
chopped         | POS: VERB       | Lemma: chop
'               | POS: PUNCT      | Lemma: '
,               | POS: PUNCT      | Lemma: ,
'               | POS: PUNCT      | Lemma: '
450             | POS: NUM        | Lemma: 450
g               | POS: NOUN       | Lemma: g
leeks           | POS: NOUN       | Lemma: leek
(               | POS: PUNCT      | Lemma: (
about           | POS: ADV        | Lemma: about
2               | POS: NUM        | Lemma: 2
medium          | POS: ADJ        | Lemma: medium
)               | POS: PUNCT      | Lemma: )
,               | POS: PUNCT      | Lemma: ,
finely          | POS: ADV        | Lemma: finely
sliced          | POS: VERB       | Lemma: slice
'               | POS: PUNCT      | Lemma: '
,               | POS: PUNCT      | Lemma: ,
'               | POS: PUNCT      | Lemma: '
2               | POS: NUM        | Lemma: 2
cloves          | POS: VERB       | Lemma: clove
garlic          | POS: ADJ        | Lemma: garlic
,               | POS: PUNCT      | Lemma: ,
crushed         | POS: VERB       | Lemma: crush
'               | POS: PUNCT      | Lemma: '
,               | POS: PUNCT      | Lemma: ,
'               | POS: PUNCT      | Lemma: '
225             | POS: NUM        | Lemma: 225
g               | POS: PROPN      | Lemma: g
arborio         | POS: PROPN      | Lemma: arborio
risotto         | POS: PROPN      | Lemma: risotto
rice            | POS: PROPN      | Lemma: rice
'               | POS: PUNCT      | Lemma: '
,               | POS: PUNCT      | Lemma: ,
'               | POS: PUNCT      | Lemma: '
2/3             | POS: NUM        | Lemma: 2/3
cup             | POS: NOUN       | Lemma: cup
dry             | POS: VERB       | Lemma: dry
white           | POS: ADJ        | Lemma: white
wine            | POS: NOUN       | Lemma: wine
'               | POS: PUNCT      | Lemma: '
,               | POS: PUNCT      | Lemma: ,
'               | POS: NUM        | Lemma: '
2               | POS: NUM        | Lemma: 2
very            | POS: ADV        | Lemma: very
low             | POS: ADJ        | Lemma: low
salt            | POS: NOUN       | Lemma: salt
vegetable       | POS: NOUN       | Lemma: vegetable
stock           | POS: NOUN       | Lemma: stock
cubes           | POS: NOUN       | Lemma: cube
dissolved       | POS: VERB       | Lemma: dissolve
in              | POS: ADP        | Lemma: in
3               | POS: NUM        | Lemma: 3
cups            | POS: NOUN       | Lemma: cup
hot             | POS: ADJ        | Lemma: hot
water           | POS: NOUN       | Lemma: water
'               | POS: PUNCT      | Lemma: '
,               | POS: PUNCT      | Lemma: ,
'               | POS: PUNCT      | Lemma: '
80              | POS: NUM        | Lemma: 80
g               | POS: NOUN       | Lemma: g
soft            | POS: ADJ        | Lemma: soft
feta            | POS: ADJ        | Lemma: feta
cheese          | POS: NOUN       | Lemma: cheese
,               | POS: PUNCT      | Lemma: ,
crumbled        | POS: VERB       | Lemma: crumble
'               | POS: PUNCT      | Lemma: '
]               | POS: PUNCT      | Lemma: ]

In [54]:
def custom_tokenizer(text):
    #text cleaning
    text = text.lower()
     # Replace unicode superscript fractions and other weird chars
    text = re.sub(r'[¼½¾⅓⅔⁄¹²³⁴⁵⁶⁷⁸⁹⁰]', ' ', text)

    # Separate numbers stuck to units or words (e.g., "100ml" → "100 ml")
    text = re.sub(r'(\d+)([a-zA-Z]+)', r'\1 \2', text)

    # Remove standalone numbers and units
    text = re.sub(r'\b\d+/?\d*\b', ' ', text)
    text = re.sub(r'\b(?:ml|l|tsp|tbsp|cup|cups|g|kg|oz|gram|grams|pinch|cm|inch|store|style)\b', '', text)

    # Remove hyphens or leading punctuation leftovers
    text = re.sub(r'^[^\w\s]+|[^\w\s]+$', '', text)

    # Remove extra symbols, keep only words
    text = re.sub(r'[^\w\s]', ' ', text)

    # Collapse multiple spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    # spacy to remove stop words and anythings except NOUN and PROPN
    # return lemmatized tokens
    text = nlp(text)
    tokens = [token.lemma_ for token in text 
              if not token.is_stop 
              and not token.is_punct 
              and token.pos_ in {'NOUN','PROPN'}]
    
    return tokens

In [55]:
for s in sample:
    print(custom_tokenizer(s))

['tablespoon', 'sunflower', 'oil', 'handful', 'sage', 'leave', 'bacon', 'rasher', 'leek', 'medium', 'clove', 'garlic', 'arborio', 'risotto', 'rice', 'wine', 'salt', 'vegetable', 'stock', 'cube', 'water', 'feta', 'cheese']
['banana', 'curd', 'dahi', 'mustard', 'sarson', 'powder', 'chilli', 'sugar', 'salt']
['potato', 'pancetta', 'bacon', 'onion', 'egg', 'tablespoon', 'tablespoon', 'milk', 'bunch', 'chive', 'tablespoon', 'sugar', 'salt', 'tomato', 'sauce']
['soy', 'oil', 'ginger', 'garlic', 'adrak', 'lehsun', 'paste', 'onion', 'turmeric', 'powder', 'haldi', 'cumin', 'seeds', 'dhania', 'jeera', 'powder', 'chilli', 'powder', 'garam', 'masala', 'fenugreek', 'kasuri', 'methi', 'garam', 'masala', 'capsicum', 'tomato', 'e', 'sugar', 'cream', 'salt', 'coriander', 'dhania']
['chana', 'dal', 'oil', 'ginger', 'adrak', 'cumin', 'jeera', 'kashmiri', 'chilli', 'piece', 'salt', 'curd', 'dahi', 'mustard', 'rai', 'sarson', 'curry', 'asafoetida', 'hing']
['almond', 'badam', 'milk', 'ghee', 'sugar', 'cardamom', 'elaichi', 'powder', 'saffron', 'kesar', 'strand', 'almond', 'badam', 'sliver']
['capsicum', 'white', 'quinoa', 'tablespoon', 'olive', 'oil', 'tablespoon', 'onion', 'clove', 'garlic', 'cut', 'piece', 'teaspoon', 'oregano', 'teaspoon', 'paprika', 'lamb', 'mince', 'green', 'olive', 'tablespoon', 'pine', 'nut', 'parsley', 'leave', 'feta', 'salad', 'leave']
['capsicum', 'medium', 'capsicum', 'medium', 'capsicum', 'wheat', 'bread', 'slice', 'bread', 'slice', 'oil', 'salt', 'herb', 'iceberg', 'lettuce', 'leave', 'paneer', 'cottage', 'cheese', 'curd', 'parsley', 'coriander', 'dhania', 'dill', 'lehsun', 'chilli']
['spinach', 'baingan', 'eggplant', 'cube', 'moong', 'dal', 'ginger', 'adrak', 'paste', 'garam', 'masala', 'turmeric', 'powder', 'haldi', 'soda', 'salt', 'oil', 'nigella', 'kalonji', 'green', 'chilli', 'turmeric', 'powder', 'haldi', 'lemon', 'juice']
['broccolini', 'bunch', 'asparagus', 'leaf', 'parsley', 'tablespoon', 'pesto', 'olive', 'oil', 'garlic', 'wholemeal', 'spelt', 'flour', 'teaspoon', 'powder', 'cheddar', 'cheese', 'egg', 'milk']

- apply it to our dataset now

In [56]:
features_exploded["ingredients"].apply(custom_tokenizer)

0       [field, bean, butter, bean, oil, cumin, jeera,...
1       [capsicum, cube, paneer, cottage, cheese, coco...
2       [onion, cashew, nut, kaju, chilli, cottage, ch...
3       [oil, vinegar, mustard, sarson, powder, salt, ...
4                        [flax, seed, lemon, juice, salt]
                              ...
3565    [skewer, tablespoon, peanut, oil, lime, juice,...
3566    [tomato, cherry, tomato, capsicum, handful, ba...
3567    [carrot, avocado, small, tuna, rice, tablespoo...
3568    [wheat, boiling, water, salt, lentil, ham, bon...
3570    [yoghurt, teaspoon, lemon, juice, teaspoon, wh...
Name: ingredients, Length: 3499, dtype: object

VECTORIZING USING tfidfVectorizer
- use min_df for filtering out rare words that don't generalize or add value (e.g., spelling errors, unique names, uncommon variants).
- use max_features to limit feature space to prevent sparsity, overfitting

Edit -- Without these hyperparameters the feature set or vocabulary was coming out to be 1576, it was also considering features with spelling errors, possibly missed during the cleaning

In [107]:
# Convert this into a vector
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(tokenizer=custom_tokenizer, min_df= 4, max_features= 800)
#Edit: ngrams is causing too much of array size (18652 features), 
#      this is more than the number of rows in our set, for now, lets take it without ngrams
tfidf_matrix = vectorizer.fit_transform(features_exploded["ingredients"])

c:\Program Files\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [108]:
# Get feature (token) names
feature_names = vectorizer.get_feature_names_out()

df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)

df_tfidf.head()

,adrak,agar,agave,agria,ajmoda,ajwain,akhrot,alfalfa,allspice,almond,...,x,xa0,yam,yeast,yellow,yoghurt,yogurt,yolk,zest,zucchini
0,0.175498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.172840,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.181584,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [109]:
feature_names

array(['adrak', 'agar', 'agave', 'agria', 'ajmoda', 'ajwain', 'akhrot',
       'alfalfa', 'allspice', 'almond', 'alsi', 'amaranth', 'amchur',
       'amla', 'anar', 'anardana', 'anchovy', 'anise', 'anjeer', 'apple',
       'approx', 'apricot', 'arborio', 'arhar', 'aril', 'asafoetida',
       'asparagus', 'atta', 'avocado', 'baby', 'backstrap', 'bacon',
       'badam', 'badi', 'bag', 'baguette', 'baingan', 'bajra', 'baking',
       'ball', 'banana', 'barbecue', 'barley', 'basil', 'basis',
       'basmati', 'baton', 'batter', 'bay', 'bean', 'beans', 'beansprout',
       'beaten', 'beef', 'beej', 'beet', 'beetroot', 'bengal', 'berry',
       'besan', 'bhaji', 'bhindi', 'bhopla', 'bird', 'biscuit', 'bite',
       'black', 'blackberry', 'blanched', 'blend', 'blueberry', 'boiling',
       'bok', 'bone', 'boneless', 'bottle', 'bran', 'bread', 'breadcrumb',
       'breast', 'brine', 'brinjal', 'broccoli', 'broccolini', 'brown',
       'brushing', 'brussels', 'buckwheat', 'bulb', 'bun', 'bunch',
       'bunche', 'bunches', 'burger', 'butter', 'buttercup', 'buttermilk',
       'butternut', 'button', 'cabbage', 'cacao', 'cajun', 'can',
       'cannellini', 'canola', 'caper', 'capscium', 'capsicum', 'caraway',
       'cardamom', 'carom', 'carrot', 'carrots', 'cashew', 'caster',
       'castor', 'cauliflower', 'cayenne', 'celery', 'chaat', 'chai',
       'chakri', 'chana', 'chapatis', 'chawal', 'chawli', 'cheddar',
       'cheek', 'cheese', 'cherry', 'chestnut', 'chia', 'chick',
       'chicken', 'chickoo', 'chilli', 'chip', 'chipotle', 'chive',
       'chocolate', 'choice', 'chorizo', 'choy', 'chunk', 'chunky',
       'chutney', 'cinnamon', 'clove', 'cluster', 'cob', 'cobs', 'cocoa',
       'coconut', 'coffee', 'coleslaw', 'colour', 'cook', 'cooking',
       'core', 'coriander', 'corn', 'cornflour', 'cottage', 'cow',
       'cracker', 'cranberry', 'cream', 'cress', 'crumb', 'crust',
       'crusty', 'cube', 'cubes', 'cucumber', 'cumin', 'curd', 'curds',
       'currant', 'curry', 'custard', 'cut', 'cutlet', 'd', 'dahi',
       'dairy', 'dal', 'dalchini', 'dalia', 'dane', 'daria', 'dark',
       'daro', 'date', 'dhania', 'diameter', 'dice', 'dietitian', 'dijon',
       'dill', 'dip', 'doctor', 'doodh', 'doodhi', 'dosa', 'dressing',
       'drizzle', 'drizzling', 'drop', 'drumstick', 'dukkah', 'dust',
       'edamame', 'eg', 'egg', 'eggplant', 'eggs', 'el', 'elaichi', 'end',
       'essence', 'extra', 'extract', 'eye', 'falafel', 'fat', 'fennel',
       'fenugreek', 'feta', 'field', 'fig', 'fillet', 'filo', 'finger',
       'firm', 'fish', 'flake', 'flatbread', 'flatleaf', 'flavour',
       'flax', 'flaxseed', 'flesh', 'floret', 'flour', 'floury', 'flower',
       'food', 'free', 'fresh', 'frond', 'frozen', 'fruit', 'fry',
       'frying', 'gai', 'garam', 'garden', 'garlic', 'garnish', 'gehun',
       'gelatine', 'gem', 'ghee', 'gherkin', 'ginger', 'glaze', 'gnocchi',
       'goat', 'gooseberry', 'gourd', 'grain', 'grainy', 'granny',
       'granola', 'granule', 'grape', 'grapefruit', 'grated', 'gravy',
       'grease', 'greek', 'green', 'greens', 'groat', 'ground', 'guava',
       'gum', 'gur', 'haldi', 'half', 'haloumi', 'ham', 'handful',
       'hanout', 'hara', 'hare', 'harissa', 'hazelnut', 'head', 'herb',
       'herbs', 'hfg', 'hing', 'hoisin', 'hoki', 'hokkien', 'honey',
       'hour', 'hummus', 'hung', 'husk', 'ice', 'iceberg', 'imli',
       'indian', 'instruction', 'jada', 'jaggery', 'jaiphal', 'jalapeño',
       'jar', 'jardalu', 'jasmine', 'jau', 'jeera', 'jelly', 'jowar',
       'juice', 'julienne', 'juliennes', 'ka', 'kabuli', 'kaddu', 'kadhi',
       'kadi', 'kaffir', 'kaju', 'kala', 'kalamata', 'kale', 'kaleslaw',
       'kalimirch', 'kalonji', 'kand', 'karela', 'kashmiri', 'kasuri',
       'ke', 'kecap', 'kele', 'kernel', 'kernels', 'kesar', 'ketchup',
       'khada', 'khajur', 'kharbooja', 'khatta', 'khoya', 'khumani',
       'khumb', 'khumbh', 'khus', 'ki', 'kidney', 'kimchi', 'king',
       'kismis', 'kit', 'kitchen', 'kiwifruit', 'knife', 'kodri', 'kokum',
       'kopra', 'korma', 'kuria', 'kurmura', 'kutti', 'kuttu', 'lady',
       'lamb', 'lan', 'lauki', 'laung', 'lavang', 'lavash', 'leaf',
       'leafy', 'lean', 'leave', 'lebanese', 'leek', 'leftover', 'leg',
       'lehsun', 'lemon', 'lemongrass', 'length', 'lengthway',
       'lengthways', 'lengthwise', 'lentil', 'lettuce', 'light', 'lime',
       'linseed', 'liquid', 'lite', 'litre', 'loin', 'long', 'low',
       'lychee', 'macadamia', 'macaroni', 'maida', 'maize', 'makai',
       'malai', 'mandarin', 'mango', 'manis', 'maple', 'marinade',
       'market', 'masala', 'masoor', 'massaman', 'matchstick', 'matki',
       'mature', 'mawa', 'mayonnaise', 'meal', 'meat', 'medallion',
       'medium', 'medjool', 'medley', 'melon', 'melt', 'methi', 'mexican',
       'microwave', 'milk', 'millet', 'mince', 'mini', 'mint', 'minute',
       'mirin', 'miso', 'mix', 'mixture', 'mm', 'moath', 'moisture',
       'mooli', 'moon', 'moong', 'moroccan', 'mozzarella', 'multigrain',
       'mung', 'muscovado', 'mushroom', 'mushrooms', 'muskmelon',
       'mustard', 'naan', 'nachni', 'nacho', 'namak', 'nariyal', 'nectar',
       'nigella', 'noodle', 'nori', 'nugget', 'null', 'nut', 'nutmeg',
       'nuts', 'oak', 'oat', 'oats', 'oil', 'olive', 'omit', 'one',
       'onion', 'optional', 'orange', 'oregano', 'oyster', 'pack',
       'packet', 'pad', 'pak', 'palak', 'palm', 'pancetta', 'panch',
       'pandi', 'paneer', 'pani', 'panko', 'papaya', 'paper', 'paprika',
       'paratha', 'parathas', 'parmesan', 'parsley', 'parsnip', 'part',
       'passata', 'passionfruit', 'pasta', 'paste', 'pastry', 'patta',
       'patti', 'pav', 'pea', 'peach', 'peanut', 'pear', 'pearl', 'peas',
       'pecan', 'penne', 'pepita', 'pepper', 'peppercorn', 'peppercorns',
       'pesto', 'phalli', 'philadelphia', 'phool', 'phoron', 'phudina',
       'pickle', 'piece', 'pinche', 'pine', 'pineapple', 'pistachio',
       'pistachios', 'pita', 'pizza', 'plain', 'plant', 'plum', 'pocket',
       'pod', 'poha', 'polenta', 'pomegranate', 'poppy', 'pork',
       'portion', 'potato', 'pouch', 'powder', 'prawn', 'pre',
       'prosciutto', 'prune', 'pudina', 'puff', 'pulp', 'pumpkin',
       'punnet', 'puree', 'purée', 'quality', 'quantity', 'quarter',
       'quinoa', 'radish', 'ragi', 'rai', 'raisin', 'rajgira', 'rajma',
       'range', 'rapeseed', 'ras', 'rasher', 'raspberry', 'rava',
       'readymade', 'recipe', 'red', 'relish', 'reserve', 'ribbon',
       'rice', 'ricotta', 'ridge', 'rind', 'ring', 'risoni', 'roast',
       'roasted', 'rocket', 'roll', 'room', 'root', 'rotis', 'round',
       'rump', 'rye', 'sachet', 'saffron', 'sage', 'salad', 'salmon',
       'salt', 'sambhar', 'sanchal', 'saragavo', 'sarson', 'sauce',
       'saunf', 'sausage', 'savoy', 'scoop', 'sea', 'season', 'seasoning',
       'seed', 'seeds', 'segment', 'self', 'semolina', 'sesame', 'sev',
       'shahjeera', 'shallot', 'shape', 'sheet', 'shell', 'sherry',
       'silk', 'silver', 'size', 'skewer', 'skim', 'skin', 'skinless',
       'slaw', 'slice', 'sliced', 'slit', 'sliver', 'small', 'smith',
       'snap', 'snow', 'soba', 'soda', 'solid', 'sonth', 'sooji', 'soup',
       'sourdough', 'soy', 'soya', 'spaghetti', 'spear', 'spelt', 'spice',
       'spinach', 'spiral', 'spit', 'split', 'spray', 'spread', 'sprig',
       'spring', 'springwater', 'sprinkling', 'sprout', 'square',
       'squash', 'squeeze', 'sriracha', 'stalk', 'star', 'steak',
       'steamed', 'stem', 'stick', 'stir', 'stock', 'strand',
       'strawberry', 'strip', 'substitute', 'sugar', 'sumac', 'sun',
       'sunflower', 'surajmukhi', 'sushi', 'sweet', 'sweetcorn',
       'sweetener', 'syrup', 't', 'tabasco', 'table', 'tablespoon',
       'tablespoons', 'taco', 'tahini', 'tail', 'tamari', 'tamarind',
       'tapioca', 'tarakihi', 'tarbuj', 'tarragon', 'taste', 'tea',
       'teaspoon', 'teaspoons', 'tejpatta', 'telegraph', 'tempeh',
       'temperature', 'tender', 'tenderloin', 'tendli', 'teriyaki',
       'thai', 'thick', 'thigh', 'thighs', 'third', 'thumb', 'thyme',
       'til', 'tin', 'tip', 'tofu', 'tomato', 'toovar', 'tortilla',
       'tortillas', 'truss', 'tulsi', 'tuna', 'turai', 'turkey',
       'turmeric', 'tzatziki', 'ukda', 'urad', 'use', 'vanilla', 'veg',
       'vegan', 'vege', 'vegetable', 'vegetarian', 'vermicelli',
       'vinaigrette', 'vine', 'vinegar', 'virgin', 'walnut', 'wasabi',
       'water', 'watercress', 'watermelon', 'wedge', 'weight', 'wheat',
       'white', 'wholegrain', 'wholemeal', 'wine', 'woody',
       'worcestershire', 'wrap', 'wrapper', 'x', 'xa0', 'yam', 'yeast',
       'yellow', 'yoghurt', 'yogurt', 'yolk', 'zest', 'zucchini'],
      dtype=object)

In [110]:
#final features 
# df_tfidf = df_tfidf.reset_index(drop=True)
# scaled_nutrients_df = scaled_nutrients_df.reset_index(drop=True)
X = scaled_nutrients_df.join(df_tfidf, rsuffix="_tfidf")
X.head()

,calories,protein,carbohydrates,fiber,fat,sodium,adrak,agar,agave,agria,...,x,xa0,yam,yeast,yellow,yoghurt,yogurt,yolk,zest,zucchini
0,-0.260191,-0.172417,0.248575,0.147648,-0.580914,-0.635467,0.175498,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-0.932307,-0.764864,-0.880430,-0.162715,-0.721422,-0.594471,0.172840,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.734097,0.058406,-0.509471,-0.096680,2.264366,-0.352277,0.181584,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-0.832323,-0.957217,-1.369665,-0.374026,0.109915,-0.663219,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-0.965635,-0.787946,-1.181498,-0.149508,-0.440407,-0.302135,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Now, we have all the features names ready, let's train the model in knn

### Model building: Finding nearest neighbours through KNN

In [111]:
from sklearn.neighbors import NearestNeighbors
knn = NearestNeighbors(n_neighbors=5, metric='cosine')
knn.fit(X)

NearestNeighbors(metric='cosine')

In [112]:
# Let's say we have the input features like :
input_nutrients ={
    'calories': 345.8,
    'protein': 18.2,
    'carbohydrates': 63.7,
    'fiber': 5.9,
    'fat': 14.4,
    'sodium': 738.5
}

# available pantry items: 
input_ingredients = "flax seeds olive oil chopped onions garlic paste adrak boiled potatoes green chili cumin powder turmeric fresh coriander lemon juice"

In [113]:
# Now using this, let's find out the most similar recipies from our data, 
# for that we have to convert the ingredients the same way using the vectorizer
input_vectorized_ingredients = vectorizer.transform([input_ingredients])
input_vectorized_ingredients

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14 stored elements and shape (1, 800)>

In [114]:
input_ingredients_df = pd.DataFrame(input_vectorized_ingredients.toarray(), columns=feature_names)
input_ingredients_df

,adrak,agar,agave,agria,ajmoda,ajwain,akhrot,alfalfa,allspice,almond,...,x,xa0,yam,yeast,yellow,yoghurt,yogurt,yolk,zest,zucchini
0,0.289942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [115]:
list(input_nutrients.values())

[345.8, 18.2, 63.7, 5.9, 14.4, 738.5]

In [116]:
input_nutrients = np.array(list(input_nutrients.values()),ndmin=2)

In [117]:
input_scaled_nutrients = scaler.transform(input_nutrients)

c:\Program Files\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [118]:
input_scaled_nutrients

array([[0.57745539, 0.43541786, 2.03347741, 0.01557843, 0.62510993,
        1.66569535]])

In [119]:
input_features = pd.DataFrame(input_scaled_nutrients,columns=scaled_nutrients_df.keys())
input_features

   calories   protein  carbohydrates     fiber      fat    sodium
0  0.577455  0.435418       2.033477  0.015578  0.62511  1.665695

In [120]:
input_features = input_features.join(input_ingredients_df, rsuffix="_tfidf")
input_features

,calories,protein,carbohydrates,fiber,fat,sodium,adrak,agar,agave,agria,...,x,xa0,yam,yeast,yellow,yoghurt,yogurt,yolk,zest,zucchini
0,0.577455,0.435418,2.033477,0.015578,0.62511,1.665695,0.289942,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [121]:
distances, indices = knn.kneighbors(input_features)

In [122]:
distances #ordered

array([[0.11025163, 0.1130775 , 0.11631772, 0.11900069, 0.11959357]])

In [123]:
indices  #indices from our df

array([[2027, 2826, 1594, 2095, 2162]])

In [124]:
# Top 5 similar recipies
df.iloc[indices.flatten()]

,name,ingredients,instructions,nutrition,time,serving_size,tags
2051,"Pumpkin, chickpea and cauliflower curry","['spray oil', '1 clove garlic', '1 red onion, ...",[' Gently fry the garlic and onion in a spray ...,"{'Calories ': '529 cal', 'Kilojoules ': '2210 ...",45 mins,4,"['Gluten-free option', 'High fibre', 'Vegetari..."
2850,"Pasta with garlicky prawns, wilted tomatoes an...","['100g wholemeal pasta spirals', '150g broccol...",['1 Cook the pasta in a large saucepan of boil...,"{'Calories ': '389 cal', 'Kilojoules ': '1624 ...",35 mins,1,"['High calcium', 'High fibre', 'High protein',..."
1594,Baked Mexican Rice with Cheese Patties recipe,"['', '3 cups cooked long grained rice', '1 tbs...",For the mexican rice Heat the oil in a deep no...,"{'Energy': '528 cal', 'Protein': '11.2 g', 'Ca...",45 Mins,4 servings,"['Non-stick Pan', 'Oven', 'Vegetarian baked In..."
2119,Hasselback sweet potatoes with crispy rosemary...,"['4 small (600g) sweet potatoes/', '¹⁄³ cup ol...","['1 Preheat the air fryer to 180°C.', '2 On a ...","{'Calories ': '433 cal', 'Kilojoules ': '1821 ...",40 mins,4,"['High calcium', 'High fibre', 'High iron', 'H..."
2186,Healthier chocolate mousse,"['100g dark chocolate (70% cocoa solids), plus...",['1 Gently melt the 100g chocolate with the ag...,"{'Calories ': '139 cal', 'Kilojoules ': '582 k...",15 mins,6,"['Gluten free', 'Low sodium', 'Family favourit..."

In [125]:
##### Create a pipeline
def top_5_recipies(cal,protein,carbs,fiber,fat,sodium, ingredients):
    input_nutrients ={
    'calories': cal,
    'protein': protein,
    'carbohydrates': carbs,
    'fiber': fiber,
    'fat': fat,
    'sodium': sodium
}
    input_vectorized_ingredients = vectorizer.transform([ingredients])
    input_ingredients_df = pd.DataFrame(input_vectorized_ingredients.toarray(), columns=feature_names)
    input_nutrients = np.array(list(input_nutrients.values()),ndmin=2)
    input_scaled_nutrients = scaler.transform(input_nutrients)
    input_nutrients_df = pd.DataFrame(input_scaled_nutrients,columns=scaled_nutrients_df.keys())
    input_features = input_nutrients_df.join(input_ingredients_df, rsuffix="_tfidf")
    distances, indices = knn.kneighbors(input_features)
    return df.iloc[indices.flatten()]

In [126]:
result = top_5_recipies(290,10,38,4.5,8,120,"rice coconut dal vegetable")

c:\Program Files\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [127]:
result1 = result[['name','ingredients','nutrition']]
for i in result1.to_records():
    print(i)

(1919, 'Easy veggie biryani', "['250g basmati rice', '400g special mixed frozen vegetables', 'a generous handful of raisins', '1 vegetable stock cube', '2 tbsp korma curry paste', 'a generous handful of roasted salted cashew nuts']", "{'kcal': '305 g', 'fat': '6 g', 'saturates': '0 g', 'carbs': '57 g', 'sugars': '0 g', 'fibre': '2 g', 'protein': '9 g', 'salt': '1.42 g'}")
(751, 'Jalfrazie Layered Brown Rice (zero Oil, Low Calorie and Diabetic)', "['1 cup chopped and boiled mixed vegetables (', 'cauliflower florets ,', '1/4 cup thinly sliced spring onions whites', '1/4 cup sliced capsicum', '1/2 cup finely chopped tomato', '1/4 cup tomato puree', '1 tbsp tomato ketchup', '1/4 tsp turmeric powder (haldi)', '1 tsp chilli powder', '1 tsp coriander-cumin seeds (dhania-jeera) powder', '1/2 tsp garam masala', '1 tsp cornflour dissolved in 1/2 cup water', 'salt to taste', '1/2 tsp sugar', '1 tsp vinegar', '3 cups cooked brown rice , refer handy tip', '2 tbsp low fat milk (99.9% fat-free)', '1 tbsp finely chopped spring onion greens']", "{'Energy': '343 cal', 'Protein': '8.1 g', 'Carbohydrates': '71.8 g', 'Fiber': '4.6 g', 'Fat': '2.5 g', 'Cholesterol': '0 mg', 'Sodium': '40.1 mg'}")
(1678, 'moong dal khichdi', "['1 cup yellow moong dal (split yellow gram)', '1 cup rice (chawal)', '1/2 tsp turmeric powder (haldi)', '10 black peppercorns (kalimirch)', 'salt to taste', '2 1/2 tbsp ghee', '', 'kadhi', 'roasted papad']", "{'Energy': '342 cal', 'Protein': '12 g', 'Carbohydrates': '54 g', 'Fiber': '4.8 g', 'Fat': '8.7 g', 'Cholesterol': '0 mg', 'Sodium': '10.3 mg'}")
(817, 'oats vegetable and brown rice khichdi recipe', "['1/2 cup quick cooking rolled oats', '3/4 cup brown rice', '2 tbsp yellow moong dal (split yellow gram) , washed and drained', '2 tsp oil', '1/2 cup finely chopped onion', '1 tsp garlic (lehsun) paste', '1/2 tsp ginger (adrak) paste', '1/4 cup chopped french beans', '1/4 cup chopped carrot', '1/4 cup green peas', '1/2 tsp chilli powder', '1/2 tsp garam masala', '2 tbsp finely chopped coriander (dhania)', 'salt to taste']", "{'Energy': '300 cal', 'Protein': '9.1 g', 'Carbohydrates': '53.2 g', 'Fiber': '5.5 g', 'Fat': '5.6 g', 'Cholesterol': '0 mg', 'Sodium': '12.1 mg'}")
(1228, 'how to cook brown rice on an open flame', "['3/4 cup brown rice', 'salt to taste']", "{'Energy': '211 cal', 'Protein': '4.4 g', 'Carbohydrates': '44.4 g', 'Fiber': '2 g', 'Fat': '1.6 g', 'Cholesterol': '0 mg', 'Sodium': '2.3 mg'}")

In [128]:
result['name'].apply(print)

Easy veggie biryani
Jalfrazie Layered Brown Rice (zero Oil, Low Calorie and Diabetic)
moong dal khichdi
oats vegetable and brown rice khichdi recipe
how to cook brown rice on an open flame

1919    None
751     None
1678    None
817     None
1228    None
Name: name, dtype: object

In [129]:
result['ingredients'].apply(print)

['250g basmati rice', '400g special mixed frozen vegetables', 'a generous handful of raisins', '1 vegetable stock cube', '2 tbsp korma curry paste', 'a generous handful of roasted salted cashew nuts']
['1 cup chopped and boiled mixed vegetables (', 'cauliflower florets ,', '1/4 cup thinly sliced spring onions whites', '1/4 cup sliced capsicum', '1/2 cup finely chopped tomato', '1/4 cup tomato puree', '1 tbsp tomato ketchup', '1/4 tsp turmeric powder (haldi)', '1 tsp chilli powder', '1 tsp coriander-cumin seeds (dhania-jeera) powder', '1/2 tsp garam masala', '1 tsp cornflour dissolved in 1/2 cup water', 'salt to taste', '1/2 tsp sugar', '1 tsp vinegar', '3 cups cooked brown rice , refer handy tip', '2 tbsp low fat milk (99.9% fat-free)', '1 tbsp finely chopped spring onion greens']
['1 cup yellow moong dal (split yellow gram)', '1 cup rice (chawal)', '1/2 tsp turmeric powder (haldi)', '10 black peppercorns (kalimirch)', 'salt to taste', '2 1/2 tbsp ghee', '', 'kadhi', 'roasted papad']
['1/2 cup quick cooking rolled oats', '3/4 cup brown rice', '2 tbsp yellow moong dal (split yellow gram) , washed and drained', '2 tsp oil', '1/2 cup finely chopped onion', '1 tsp garlic (lehsun) paste', '1/2 tsp ginger (adrak) paste', '1/4 cup chopped french beans', '1/4 cup chopped carrot', '1/4 cup green peas', '1/2 tsp chilli powder', '1/2 tsp garam masala', '2 tbsp finely chopped coriander (dhania)', 'salt to taste']
['3/4 cup brown rice', 'salt to taste']

1919    None
751     None
1678    None
817     None
1228    None
Name: ingredients, dtype: object

In [130]:
result['nutrition'].apply(print)

{'kcal': '305 g', 'fat': '6 g', 'saturates': '0 g', 'carbs': '57 g', 'sugars': '0 g', 'fibre': '2 g', 'protein': '9 g', 'salt': '1.42 g'}
{'Energy': '343 cal', 'Protein': '8.1 g', 'Carbohydrates': '71.8 g', 'Fiber': '4.6 g', 'Fat': '2.5 g', 'Cholesterol': '0 mg', 'Sodium': '40.1 mg'}
{'Energy': '342 cal', 'Protein': '12 g', 'Carbohydrates': '54 g', 'Fiber': '4.8 g', 'Fat': '8.7 g', 'Cholesterol': '0 mg', 'Sodium': '10.3 mg'}
{'Energy': '300 cal', 'Protein': '9.1 g', 'Carbohydrates': '53.2 g', 'Fiber': '5.5 g', 'Fat': '5.6 g', 'Cholesterol': '0 mg', 'Sodium': '12.1 mg'}
{'Energy': '211 cal', 'Protein': '4.4 g', 'Carbohydrates': '44.4 g', 'Fiber': '2 g', 'Fat': '1.6 g', 'Cholesterol': '0 mg', 'Sodium': '2.3 mg'}

1919    None
751     None
1678    None
817     None
1228    None
Name: nutrition, dtype: object

- the model seems to work decently, however if we have more recipies, it will give better result

In [131]:
# another try 
result = top_5_recipies(290,10,38,4.5,8,120,"yogurt lettuce cheeze spinach")

c:\Program Files\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [132]:
result['name'].apply(print)

Mumbai potato wraps with minted yogurt relish
Strawberry and cinnamon muffins
Salt and pepper tofu
Onion & butternut bhajis with rotis, mango raita & mint salad
mashed potatoes recipe

1929    None
2989    None
2323    None
1920    None
1088    None
Name: name, dtype: object

In [133]:
result['ingredients'].apply(print)

['2 tsp sunflower oil', '1 onion sliced', '2 tbsp medium curry powder', '400g can chopped tomato', '750g potato diced', '2 tbsp spiced mango chutney plus extra to serve', '100g low-fat natural yogurt', '1 tsp mint sauce from a jar', '8 small plain chapatis', 'coriander sprigs, to serve']
['¾ cup self-raising flour', '¾ teaspoon ground cinnamon', '3 tablespoons', 'or ½ teaspoon liquid stevia (see tip)', '¼ cup plus 1 tablespoon reduced-fat spread, melted and cooled', '1 egg', '4 tablespoons skim milk', '2⅓ cups fresh strawberries, hulled (or use frozen strawberries, thawed), ⅓ cup chopped, the rest halved', 'sugar, to dust (optional)']
['2 x 300g packets firm, light silken tofu, cut into thick triangles', '1½ tablespoons tapioca flour', '1 teaspoon reduced-salt vegetable stock powder', '1 teaspoon white pepper', '1 red or green chilli (optional), finely chopped', '3 teaspoons olive oil', '315g Asian salad kit', '2 x 250g pouches microwavable black rice, cooked', '60g baby']
['10 rotis sprinkled with water, wrapped in baking parchment and warmed in a low oven (or following pack instructions)', '3 Little Gem lettuces shredded', '¼ cucumber thinly sliced', 'small bunch mint leaves picked', '½ lemon']
['4 medium boiled and peeled potato', '2 tsp olive oil', 'salt and to taste']

1929    None
2989    None
2323    None
1920    None
1088    None
Name: ingredients, dtype: object

In [134]:
result['nutrition'].apply(print)

{'kcal': '485 g', 'fat': '7 g', 'saturates': '3 g', 'carbs': '87 g', 'sugars': '14 g', 'fibre': '9 g', 'protein': '13 g', 'salt': '1 g'}
{'Calories ': '150 cal', 'Kilojoules ': '628 kJ', 'Protein ': '3.5 g', 'Total fat ': '4.4 g', 'Saturated fat ': '1.1 g', 'Carbohydrates ': '26.8 g', 'Sugar ': '14.1 g', 'Dietary fibre ': '1.5 g', 'Sodium ': '158 mg', ' Calcium ': 'N/S', 'Iron ': '1 mg'}
{'Calories ': '449 cal', 'Kilojoules ': '1875 kJ', 'Protein ': '15.4 g', 'Total fat ': '11.2 g', 'Saturated fat ': '1.4 g', 'Carbohydrates ': '67.2 g', 'Sugar ': '7.6 g', 'Dietary fibre ': '9.0 g', 'Sodium ': '610 mg', 'Calcium ': '118 mg', 'Iron ': '3.7 mg'}
{'kcal': '328 g', 'fat': '11 g', 'saturates': '2 g', 'carbs': '50 g', 'sugars': '10 g', 'fibre': '4 g', 'protein': '8 g', 'salt': '0.7 g'}
{'Energy': '459 cal', 'Protein': '6.1 g', 'Carbohydrates': '85.9 g', 'Fiber': '6.5 g', 'Fat': '10.4 g', 'Cholesterol': '0 mg', 'Sodium': '41.8 mg'}

1929    None
2989    None
2323    None
1920    None
1088    None
Name: nutrition, dtype: object

In [137]:
# save the knn model and vectorizors
import pickle 
with open("knn.pkl",'wb') as f:
    pickle.dump(knn,f)
with open("ingredient_vectorizer.pkl",'wb') as f:
    pickle.dump(vectorizer,f)
with open("nutrients_scaler.pkl",'wb') as f:
    pickle.dump(scaler,f)